### ISSUE TITLE
Support for Entra External ID (CIAM)

### ISSUE THREAD

**Issue by gjoshevski** [hashicorp/terraform-provider-azuread#1263]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for Entra External ID. 
https://learn.microsoft.com/en-us/entra/external-id/customers/overview-customers-ciam

**Comment by Pieeer1** [comment]
This will require the user impersonation scope. 

https://learn.microsoft.com/en-us/rest/api/activedirectory/ciam-tenants/create?view=rest-activedirectory-2023-05-17-preview&tabs=HTTP

 This may be good to include some functionality to either pass in an existing bearer token to allow for autonomous runs on the cloud with "delegated" access.

**Comment by JoelCanteroGCO** [comment]
Any update yet?

**Comment by Pieeer1** [comment]
> right now i'am creating the resource using the azapi resource. Unfortunately this means terraform must run twice because it does not know about its not-yet-created tenant_id needed for the azuread provider. Generally, the azuread provider works well for Entra external ID.
> 
> ```
> resource "azapi_resource" "entra-external-id" {
>   type = "Microsoft.AzureActiveDirectory/ciamDirectories@2023-05-17-preview"
>   name = "myfancyciamdirectory"
>   location = "europe"
>   parent_id = azurerm_resource_group.my_resourcegroup.id
>   body = jsonencode({
>   sku = {
>    name = "Base"
>    tier = "A0"
>  }
> 
>     properties = {
>       createTenantProperties = {
>         countryCode = "CH"
>         displayName = "My fancy CIAM"
>       }
>     }
>   })
>   response_export_values = ["properties.tenantId"]
> }
> ```
> 
> tenantId then is accessible trough: `jsondecode(azapi_resource.entra-external-id.output).properties.tenantId`


This is a correct assumption, the main problem is really related to the user_impersonation scope requirement for the creation and modification of the resources. That token cannot be generated using an automated process, as it has to have a user login as its entry point. This makes cloud deployments difficult, the only workaround I had was to manually pass a user impersonation token at runtime to my pipeline. 

At the end of the day my resolution was to NOT put this under IAC. Which is really frustrating. I think the tenant creation ideally needs to be moved under a scope that can be automated, or there needs to be some special process here, but that is a Microsoft discussion.

**Comment by Pieeer1** [comment]
I have found a workaround in doing this in github actions and automated pipelines. 

Deploying this requires the `user_impersonation` scope which as previously discussed requires an actual user login to function. Deployments on the cloud traditionally use a service principal, which are unable to request that scope. This can be bypassed by using a device code authentication process.

Here is what I have in my actions file:


```
  - name: Login to Azure CLI with device code flow. 
            run: |
              az login --use-device-code
            timeout-minutes: 5 #since this requires manual intervention, we should timeout after 5 minutes
    
          - name: Install Terraform
            uses: hashicorp/setup-terraform@v3
            with: 
                terraform_version: ${{ env.terraform-version }}
    
          - name: Set env vars
            run: # REDACTED 
              
          - name: Install Terragrunt
            uses: autero1/action-terragrunt@v3
            with:
                terragrunt-version: ${{ env.terragrunt-version }}
                token: ${{ secrets.GITHUB_TOKEN }}
    
          - name: Terragrunt Init
            working-directory: ./.infrastructure/envs/${{inputs.environment_name}}/${{inputs.terragrunt_module}}
            run: terragrunt init
    
          - name: Terragrunt Plan
            working-directory: ./.infrastructure/envs/${{inputs.environment_name}}/${{inputs.terragrunt_module}}
            run: terragrunt plan -out ../../../${{inputs.terragrunt_module}}-${{inputs.environment_name}}.tfplan # Terragrunt puts the plan in a 3 deep directory in the cache :/ this is a workaround
    
```

I use the azapi provider as shown by @mm-supernice as such:

```
resource "azapi_resource" "entra-external-id" {
  type = "Microsoft.AzureActiveDirectory/ciamDirectories@2023-05-17-preview"
  create_query_parameters = {
    "resourceGroupName" = [azurerm_resource_group.rg.name]
    "subscriptionId"    = [var.subscription_id]
    "name" : ["${var.subdomain_name}"]
  }
  name      = "${var.app_name} ${var.env_name} CIAM Tenant"
  location  = "westus"
  parent_id = azurerm_resource_group.rg.id
  body = jsonencode({
    sku = {
      name = "Base"
      tier = "A0"
    }
    properties = {
      createTenantProperties = {
        countryCode = "US"
        displayName = "${var.app_name} ${var.env_name} CIAM Tenant"
      }
    }
  })
  response_export_values = ["properties.tenantId"]
}

```

When the pipeline runs, you have 5 minutes to enter the device code using the code provided in the pipelines. This will then authenticate back into the system as a user_impersonation token with the signing user's scope, which will in turn allow the pipeline to actually deploy this functionality.
