### ISSUE TITLE
Assigning Users or Groups to an Enterprise Application in Azure

### ISSUE THREAD

**Issue by VF-mbrauer** [hashicorp/terraform-provider-azuread#164]
With help of the `azuread` Provider I am able to create an application, and create also a service Principle for the same to make it an Enterprise Application.

Now I need to assign `Users and Groups` to that Enterprise Application to create specific permissions. I was not able to find the documentation or implementation details for that.
Any suggestions?

**Comment by matsest** [comment]
Is not this done by `app_role` in `azuread_application`? you use for the `service_principal` ?

https://www.terraform.io/docs/providers/azuread/r/application.html

**Comment by drdamour** [comment]
@matsest not, app role only defines the roles in the app registry, then users/groups are added to the roles via the service prinicpal

**Comment by no-acl** [comment]
Also very interested in this

**Comment by PfisterAn** [comment]
+1 -- appears to be not feasible atm.
I was also not able to find a way achieving this through the `az ad`-cli, which would at least provide the possibility to use i.e. the external provider in the meantime.

**Comment by manicminer** [comment]
Thanks for requesting this feature!

User/group role assignments are accomplished only through the Microsoft Graph API. We currently cannot use MS Graph due to lack of SDK support, however I have marked this as a valid feature request for when we are able to.

This is closely related, but different, to #17 

API resource: https://docs.microsoft.com/en-us/graph/api/serviceprincipal-list-approleassignedto?view=graph-rest-beta&tabs=http

**Comment by drdamour** [comment]
is there an upstream issue to watch/vote?

**Comment by waqark3389** [comment]
+1

**Comment by waqark3389** [comment]
@drdamour https://github.com/Azure/azure-sdk-for-go/issues/7352

**Comment by JoeSainsburys** [comment]
Whilst we wait for it to be officially supported, you can just hit the REST API directly. It's not the prettiest but this seems to work:


```hcl

resource "azuread_service_principal" "login_app" {
  application_id               = azuread_application.login_app.application_id
  app_role_assignment_required = true
}
data "azuread_group" "k8s_users" {
  name = "nameremoved"
}
resource "null_resource" "login_app_group" {
  triggers = {
    group_id    = data.azuread_group.k8s_users.id
    resource_id = azuread_service_principal.login_app.object_id
    app_role_id = "00000000-0000-0000-0000-000000000000"
  }
  provisioner "local-exec" {
    command = "az rest --method POST --uri https://graph.microsoft.com/v1.0/servicePrincipals/${self.triggers.resource_id}/appRoleAssignedTo --body \"{ 'appRoleId': '${self.triggers.app_role_id}', 'principalId': '${self.triggers.group_id}','resourceId': '${self.triggers.resource_id}'}\" --headers \"Content-Type=application/json\""
  }
  provisioner "local-exec" {
    # This file should always have LF line endings! Otherwise bash will have issues
    # We essentially just rely on json props being in alpha order here, jq would be better for this but it isn't always installed
    interpreter = ["bash", "-c"]
    command     = <<-EOC
		set -eo pipefail
		assignment_id=`az rest --method GET --uri 'https://graph.microsoft.com/v1.0/servicePrincipals/${self.triggers.resource_id}/appRoleAssignedTo' \
		 | grep -P '("id")|("principalId")' \
		 | grep "${self.triggers.group_id}" -B1 \
		 | head -n 1 \
		 | grep -Po '[a-zA-Z0-9\-_]{10,}'`
		echo "Deleting assignment $assignment_id"
		az rest --method DELETE --uri "https://graph.microsoft.com/v1.0/servicePrincipals/${self.triggers.resource_id}/appRoleAssignedTo/$assignment_id"
		EOC
    when        = destroy
  }
  depends_on = ["azuread_service_principal.login_app"]
}

```

**Comment by randywallace** [comment]
Using [Scott Winkler's Shell Provider](https://registry.terraform.io/providers/scottwinkler/shell/latest/docs/resources/shell_script_resource) I put together a module that is working for my purposes.  I hope that anyone else tackling this problem finds this useful.  

```shell
variable object_id {
  type        = string
  description = "Azure AD Object ID"
}

variable resource_id {
  type        = string
  description = "Enterprise Application ID"
}

variable app_role_id {
  type        = string
  description = "GUID of App Role configured on Azure AD Application Registration"
}

resource shell_script this {
  lifecycle_commands {
    create = <<EOF
    az rest --method POST --uri https://graph.microsoft.com/v1.0/servicePrincipals/$resource_id/appRoleAssignedTo --body "{'appRoleId':'$app_role_id','principalId':'$group_id','resourceId':'$resource_id'}" --headers 'Content-Type=application/json' --query '{"id": id}'
EOF
    read = <<EOF
application_id=$(jq -r .id < /dev/stdin)
az rest --method GET --uri https://graph.microsoft.com/v1.0/servicePrincipals/$resource_id/appRoleAssignedTo/$application_id --headers 'Content-Type=application/json' --query '{"id": id}'
EOF
    delete = <<EOF
application_id=$(jq -r .id < /dev/stdin)
az rest --method DELETE --uri https://graph.microsoft.com/v1.0/servicePrincipals/$resource_id/appRoleAssignedTo/$application_id
EOF
  }

  environment = {
    group_id    = var.object_id
    resource_id = var.resource_id
    app_role_id = var.app_role_id
  }
}

output assignment_id {
  value = shell_script.this.id
}
```

**Comment by bryancpowell** [comment]
This REALLY needs to be supported IMHO, it is a significant component of Azure management and we would like to transition it to IAC

**Comment by CaptainStealthy** [comment]
> @drdamour [Azure/azure-sdk-for-go#7352](https://github.com/Azure/azure-sdk-for-go/issues/7352)

So is the above linked issue actually needed for this to happen?

Or will v2.0 of the provider essentially solve this? Comments in #323 suggest that this provider will use its own Azure SDK, as opposed to the official one.

**Comment by manicminer** [comment]
No it isn't, we're moving away from the Azure SDK for this provider.

**Comment by t-l-k** [comment]
@JoeSainsburys  and @randywallace great contributions, thanks, question though: this relies on the ambient Azure CLI authentication credential, right?

Users who may wish to use the same access token that is in use, by say, the `azurerm` provider, are going to have a challenge to get said access token out of said provider (and even then, has it all the necessary scopes).

Will throw up some challenges when run on automation agents which may not persist an ambient authenticated Azure CLI session. This seems to be the common problem I run into when introducing scriptable resources.

**Comment by manicminer** [comment]
Correct, for the workarounds above you are going to need a valid token in place for Azure CLI

**Comment by randywallace** [comment]
yep; this isn't the only case where we need the AZ CLI (specifically `az rest ...`); we could build some custom things, but this works for our purposes; note that if you run this on Azure (like AKS/ACI/AppServices/et al.), that it would require (via MSI) an `az login --identity` which could streamline things? As via MSI (and specifically the various MSI Metadata endpoints depending on what you're running on) the whole token game is up to Azure, regardless of whether you're using the azure provider(s) or az cli.

**Comment by treyhendon** [comment]
Recently ran into this while trying to setup Grafana access in our infrastructure code.  Had to use [New-AzureADGroupAppRoleAssignment](https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadgroupapproleassignment?view=azureadps-2.0) via the AzureAD PowerShell tool to assign AAD Security Groups to the provider created Grafana App Roles.

**Comment by CaptainStealthy** [comment]
For anyone that needs to do this in CI/CD, using the comments above (and a lot of Google-fu!), I managed to put together a YAML template that will do this in Azure Pipelines:

```yaml
```

**Comment by CaptainStealthy** [comment]
For anyone that needs to do this in CI/CD, using the comments above (and a lot of Google-fu!), I managed to put together a YAML template that will do this in Azure Pipelines.

I simply run this step in the deployment pipeline immediately following the `terraform apply` step. The Terraform step won't have the Azure CLI token available, but if you add the `AzureCLI@2` step afterwards, Azure DevOps will automatically authenticate the CLI for you. 👍 

```yaml
parameters:
  azureServiceConnectionName: ''
  servicePrincipalId: ''
  principalId: ''
  appRoleId: '00000000-0000-0000-0000-000000000000'

steps:
  - task: AzureCLI@2
    displayName: Add App Role Assignment
    inputs:
      azureSubscription: ${{ parameters.azureServiceConnectionName }}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        $appId = "${{ parameters.servicePrincipalId }}";
        $principalId = "${{ parameters.principalId }}";
        $appRoleId = "${{ parameters.appRoleId }}";

        # Check if role assignment already exists
        $roleAssignments = az rest --method GET `
        --uri https://graph.microsoft.com/v1.0/servicePrincipals/$appId/appRoleAssignedTo `
        --headers 'Content-Type=application/json' --output json `
        --query "value[?principalId=='$principalId']" | ConvertFrom-Json;

        # Add role assignment if the GET call returns an empty array
        if ($roleAssignments.Length -eq 0) {
          az rest --method POST `
          --uri https://graph.microsoft.com/v1.0/servicePrincipals/$appId/appRoleAssignedTo `
          --body "{ 'appRoleId': '$appRoleId', 'principalId': '$principalId', 'resourceId': '$appId'}" `
          --headers "Content-Type=application/json";
        }
```
