### ISSUE TITLE
GitHub action OIDC Auth doesn't work with v2.28.0

### ISSUE THREAD

**Issue by Satak** [hashicorp/terraform-provider-azuread#875]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritise this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritise the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureAD Provider) Version

- Terraform version, latest
- AzureAD provider `2.28.0`

### Affected Resource(s)

OIDC auth

### Terraform Configuration Files

```hcl
provider "azuread" {}
```

```yaml
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true
  TF_IN_AUTOMATION: true
  ARM_SKIP_PROVIDER_REGISTRATION: true

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write
```

### Debug Output

```
Error: building client: unable to obtain access token: clientAssertionAuthorizer: cannot parse certificate: x509: malformed certificate

  with provider["registry.terraform.io/hashicorp/azuread"],
  on main.tf line 5, in provider "azuread":
   5: provider "azuread" {}
```

### Expected Behavior

OIDC auth should work as 2.27

### Actual Behavior

Can't run terraform plan or apply since the oidc auth from github action doesn't work with azuread provider 2.28. 2.27 works.
